# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/prj/Utility

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/prj/Utility

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/prj/Utility/CMakeFiles /storage/emulated/0/prj/Utility//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/prj/Utility/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Utility_test

# Build rule for target.
Utility_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Utility_test
.PHONY : Utility_test

# fast build rule for target.
Utility_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/build
.PHONY : Utility_test/fast

#=============================================================================
# Target rules for targets named Utility

# Build rule for target.
Utility: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Utility
.PHONY : Utility

# fast build rule for target.
Utility/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/build
.PHONY : Utility/fast

main/src/codec/hasher.o: main/src/codec/hasher.cpp.o
.PHONY : main/src/codec/hasher.o

# target to build an object file
main/src/codec/hasher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/codec/hasher.cpp.o
.PHONY : main/src/codec/hasher.cpp.o

main/src/codec/hasher.i: main/src/codec/hasher.cpp.i
.PHONY : main/src/codec/hasher.i

# target to preprocess a source file
main/src/codec/hasher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/codec/hasher.cpp.i
.PHONY : main/src/codec/hasher.cpp.i

main/src/codec/hasher.s: main/src/codec/hasher.cpp.s
.PHONY : main/src/codec/hasher.s

# target to generate assembly for a file
main/src/codec/hasher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/codec/hasher.cpp.s
.PHONY : main/src/codec/hasher.cpp.s

main/src/codec/json.o: main/src/codec/json.cpp.o
.PHONY : main/src/codec/json.o

# target to build an object file
main/src/codec/json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/codec/json.cpp.o
.PHONY : main/src/codec/json.cpp.o

main/src/codec/json.i: main/src/codec/json.cpp.i
.PHONY : main/src/codec/json.i

# target to preprocess a source file
main/src/codec/json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/codec/json.cpp.i
.PHONY : main/src/codec/json.cpp.i

main/src/codec/json.s: main/src/codec/json.cpp.s
.PHONY : main/src/codec/json.s

# target to generate assembly for a file
main/src/codec/json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/codec/json.cpp.s
.PHONY : main/src/codec/json.cpp.s

main/src/math/BigDecimal.o: main/src/math/BigDecimal.cpp.o
.PHONY : main/src/math/BigDecimal.o

# target to build an object file
main/src/math/BigDecimal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/BigDecimal.cpp.o
.PHONY : main/src/math/BigDecimal.cpp.o

main/src/math/BigDecimal.i: main/src/math/BigDecimal.cpp.i
.PHONY : main/src/math/BigDecimal.i

# target to preprocess a source file
main/src/math/BigDecimal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/BigDecimal.cpp.i
.PHONY : main/src/math/BigDecimal.cpp.i

main/src/math/BigDecimal.s: main/src/math/BigDecimal.cpp.s
.PHONY : main/src/math/BigDecimal.s

# target to generate assembly for a file
main/src/math/BigDecimal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/BigDecimal.cpp.s
.PHONY : main/src/math/BigDecimal.cpp.s

main/src/math/BigInteger.o: main/src/math/BigInteger.cpp.o
.PHONY : main/src/math/BigInteger.o

# target to build an object file
main/src/math/BigInteger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/BigInteger.cpp.o
.PHONY : main/src/math/BigInteger.cpp.o

main/src/math/BigInteger.i: main/src/math/BigInteger.cpp.i
.PHONY : main/src/math/BigInteger.i

# target to preprocess a source file
main/src/math/BigInteger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/BigInteger.cpp.i
.PHONY : main/src/math/BigInteger.cpp.i

main/src/math/BigInteger.s: main/src/math/BigInteger.cpp.s
.PHONY : main/src/math/BigInteger.s

# target to generate assembly for a file
main/src/math/BigInteger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/BigInteger.cpp.s
.PHONY : main/src/math/BigInteger.cpp.s

main/src/math/ComplexNumber.o: main/src/math/ComplexNumber.cpp.o
.PHONY : main/src/math/ComplexNumber.o

# target to build an object file
main/src/math/ComplexNumber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/ComplexNumber.cpp.o
.PHONY : main/src/math/ComplexNumber.cpp.o

main/src/math/ComplexNumber.i: main/src/math/ComplexNumber.cpp.i
.PHONY : main/src/math/ComplexNumber.i

# target to preprocess a source file
main/src/math/ComplexNumber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/ComplexNumber.cpp.i
.PHONY : main/src/math/ComplexNumber.cpp.i

main/src/math/ComplexNumber.s: main/src/math/ComplexNumber.cpp.s
.PHONY : main/src/math/ComplexNumber.s

# target to generate assembly for a file
main/src/math/ComplexNumber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/ComplexNumber.cpp.s
.PHONY : main/src/math/ComplexNumber.cpp.s

main/src/math/Matrix.o: main/src/math/Matrix.cpp.o
.PHONY : main/src/math/Matrix.o

# target to build an object file
main/src/math/Matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/Matrix.cpp.o
.PHONY : main/src/math/Matrix.cpp.o

main/src/math/Matrix.i: main/src/math/Matrix.cpp.i
.PHONY : main/src/math/Matrix.i

# target to preprocess a source file
main/src/math/Matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/Matrix.cpp.i
.PHONY : main/src/math/Matrix.cpp.i

main/src/math/Matrix.s: main/src/math/Matrix.cpp.s
.PHONY : main/src/math/Matrix.s

# target to generate assembly for a file
main/src/math/Matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/math/Matrix.cpp.s
.PHONY : main/src/math/Matrix.cpp.s

main/src/sorting/algorithm/bubble_sort.o: main/src/sorting/algorithm/bubble_sort.cpp.o
.PHONY : main/src/sorting/algorithm/bubble_sort.o

# target to build an object file
main/src/sorting/algorithm/bubble_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/bubble_sort.cpp.o
.PHONY : main/src/sorting/algorithm/bubble_sort.cpp.o

main/src/sorting/algorithm/bubble_sort.i: main/src/sorting/algorithm/bubble_sort.cpp.i
.PHONY : main/src/sorting/algorithm/bubble_sort.i

# target to preprocess a source file
main/src/sorting/algorithm/bubble_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/bubble_sort.cpp.i
.PHONY : main/src/sorting/algorithm/bubble_sort.cpp.i

main/src/sorting/algorithm/bubble_sort.s: main/src/sorting/algorithm/bubble_sort.cpp.s
.PHONY : main/src/sorting/algorithm/bubble_sort.s

# target to generate assembly for a file
main/src/sorting/algorithm/bubble_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/bubble_sort.cpp.s
.PHONY : main/src/sorting/algorithm/bubble_sort.cpp.s

main/src/sorting/algorithm/insertion_sort.o: main/src/sorting/algorithm/insertion_sort.cpp.o
.PHONY : main/src/sorting/algorithm/insertion_sort.o

# target to build an object file
main/src/sorting/algorithm/insertion_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/insertion_sort.cpp.o
.PHONY : main/src/sorting/algorithm/insertion_sort.cpp.o

main/src/sorting/algorithm/insertion_sort.i: main/src/sorting/algorithm/insertion_sort.cpp.i
.PHONY : main/src/sorting/algorithm/insertion_sort.i

# target to preprocess a source file
main/src/sorting/algorithm/insertion_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/insertion_sort.cpp.i
.PHONY : main/src/sorting/algorithm/insertion_sort.cpp.i

main/src/sorting/algorithm/insertion_sort.s: main/src/sorting/algorithm/insertion_sort.cpp.s
.PHONY : main/src/sorting/algorithm/insertion_sort.s

# target to generate assembly for a file
main/src/sorting/algorithm/insertion_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/insertion_sort.cpp.s
.PHONY : main/src/sorting/algorithm/insertion_sort.cpp.s

main/src/sorting/algorithm/merge_sort.o: main/src/sorting/algorithm/merge_sort.cpp.o
.PHONY : main/src/sorting/algorithm/merge_sort.o

# target to build an object file
main/src/sorting/algorithm/merge_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/merge_sort.cpp.o
.PHONY : main/src/sorting/algorithm/merge_sort.cpp.o

main/src/sorting/algorithm/merge_sort.i: main/src/sorting/algorithm/merge_sort.cpp.i
.PHONY : main/src/sorting/algorithm/merge_sort.i

# target to preprocess a source file
main/src/sorting/algorithm/merge_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/merge_sort.cpp.i
.PHONY : main/src/sorting/algorithm/merge_sort.cpp.i

main/src/sorting/algorithm/merge_sort.s: main/src/sorting/algorithm/merge_sort.cpp.s
.PHONY : main/src/sorting/algorithm/merge_sort.s

# target to generate assembly for a file
main/src/sorting/algorithm/merge_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/merge_sort.cpp.s
.PHONY : main/src/sorting/algorithm/merge_sort.cpp.s

main/src/sorting/algorithm/selection_sort.o: main/src/sorting/algorithm/selection_sort.cpp.o
.PHONY : main/src/sorting/algorithm/selection_sort.o

# target to build an object file
main/src/sorting/algorithm/selection_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/selection_sort.cpp.o
.PHONY : main/src/sorting/algorithm/selection_sort.cpp.o

main/src/sorting/algorithm/selection_sort.i: main/src/sorting/algorithm/selection_sort.cpp.i
.PHONY : main/src/sorting/algorithm/selection_sort.i

# target to preprocess a source file
main/src/sorting/algorithm/selection_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/selection_sort.cpp.i
.PHONY : main/src/sorting/algorithm/selection_sort.cpp.i

main/src/sorting/algorithm/selection_sort.s: main/src/sorting/algorithm/selection_sort.cpp.s
.PHONY : main/src/sorting/algorithm/selection_sort.s

# target to generate assembly for a file
main/src/sorting/algorithm/selection_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/main/src/sorting/algorithm/selection_sort.cpp.s
.PHONY : main/src/sorting/algorithm/selection_sort.cpp.s

test/src/codec/codec_test.o: test/src/codec/codec_test.cpp.o
.PHONY : test/src/codec/codec_test.o

# target to build an object file
test/src/codec/codec_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/codec/codec_test.cpp.o
.PHONY : test/src/codec/codec_test.cpp.o

test/src/codec/codec_test.i: test/src/codec/codec_test.cpp.i
.PHONY : test/src/codec/codec_test.i

# target to preprocess a source file
test/src/codec/codec_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/codec/codec_test.cpp.i
.PHONY : test/src/codec/codec_test.cpp.i

test/src/codec/codec_test.s: test/src/codec/codec_test.cpp.s
.PHONY : test/src/codec/codec_test.s

# target to generate assembly for a file
test/src/codec/codec_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/codec/codec_test.cpp.s
.PHONY : test/src/codec/codec_test.cpp.s

test/src/codec/hasher_test.o: test/src/codec/hasher_test.cpp.o
.PHONY : test/src/codec/hasher_test.o

# target to build an object file
test/src/codec/hasher_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/codec/hasher_test.cpp.o
.PHONY : test/src/codec/hasher_test.cpp.o

test/src/codec/hasher_test.i: test/src/codec/hasher_test.cpp.i
.PHONY : test/src/codec/hasher_test.i

# target to preprocess a source file
test/src/codec/hasher_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/codec/hasher_test.cpp.i
.PHONY : test/src/codec/hasher_test.cpp.i

test/src/codec/hasher_test.s: test/src/codec/hasher_test.cpp.s
.PHONY : test/src/codec/hasher_test.s

# target to generate assembly for a file
test/src/codec/hasher_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/codec/hasher_test.cpp.s
.PHONY : test/src/codec/hasher_test.cpp.s

test/src/main.o: test/src/main.cpp.o
.PHONY : test/src/main.o

# target to build an object file
test/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/main.cpp.o
.PHONY : test/src/main.cpp.o

test/src/main.i: test/src/main.cpp.i
.PHONY : test/src/main.i

# target to preprocess a source file
test/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/main.cpp.i
.PHONY : test/src/main.cpp.i

test/src/main.s: test/src/main.cpp.s
.PHONY : test/src/main.s

# target to generate assembly for a file
test/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/main.cpp.s
.PHONY : test/src/main.cpp.s

test/src/math/BigInteger_test.o: test/src/math/BigInteger_test.cpp.o
.PHONY : test/src/math/BigInteger_test.o

# target to build an object file
test/src/math/BigInteger_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/BigInteger_test.cpp.o
.PHONY : test/src/math/BigInteger_test.cpp.o

test/src/math/BigInteger_test.i: test/src/math/BigInteger_test.cpp.i
.PHONY : test/src/math/BigInteger_test.i

# target to preprocess a source file
test/src/math/BigInteger_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/BigInteger_test.cpp.i
.PHONY : test/src/math/BigInteger_test.cpp.i

test/src/math/BigInteger_test.s: test/src/math/BigInteger_test.cpp.s
.PHONY : test/src/math/BigInteger_test.s

# target to generate assembly for a file
test/src/math/BigInteger_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/BigInteger_test.cpp.s
.PHONY : test/src/math/BigInteger_test.cpp.s

test/src/math/ComplexNumber_test.o: test/src/math/ComplexNumber_test.cpp.o
.PHONY : test/src/math/ComplexNumber_test.o

# target to build an object file
test/src/math/ComplexNumber_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/ComplexNumber_test.cpp.o
.PHONY : test/src/math/ComplexNumber_test.cpp.o

test/src/math/ComplexNumber_test.i: test/src/math/ComplexNumber_test.cpp.i
.PHONY : test/src/math/ComplexNumber_test.i

# target to preprocess a source file
test/src/math/ComplexNumber_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/ComplexNumber_test.cpp.i
.PHONY : test/src/math/ComplexNumber_test.cpp.i

test/src/math/ComplexNumber_test.s: test/src/math/ComplexNumber_test.cpp.s
.PHONY : test/src/math/ComplexNumber_test.s

# target to generate assembly for a file
test/src/math/ComplexNumber_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/ComplexNumber_test.cpp.s
.PHONY : test/src/math/ComplexNumber_test.cpp.s

test/src/math/math_test.o: test/src/math/math_test.cpp.o
.PHONY : test/src/math/math_test.o

# target to build an object file
test/src/math/math_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/math_test.cpp.o
.PHONY : test/src/math/math_test.cpp.o

test/src/math/math_test.i: test/src/math/math_test.cpp.i
.PHONY : test/src/math/math_test.i

# target to preprocess a source file
test/src/math/math_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/math_test.cpp.i
.PHONY : test/src/math/math_test.cpp.i

test/src/math/math_test.s: test/src/math/math_test.cpp.s
.PHONY : test/src/math/math_test.s

# target to generate assembly for a file
test/src/math/math_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/math_test.cpp.s
.PHONY : test/src/math/math_test.cpp.s

test/src/math/test/Matrix_test.o: test/src/math/test/Matrix_test.cpp.o
.PHONY : test/src/math/test/Matrix_test.o

# target to build an object file
test/src/math/test/Matrix_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/test/Matrix_test.cpp.o
.PHONY : test/src/math/test/Matrix_test.cpp.o

test/src/math/test/Matrix_test.i: test/src/math/test/Matrix_test.cpp.i
.PHONY : test/src/math/test/Matrix_test.i

# target to preprocess a source file
test/src/math/test/Matrix_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/test/Matrix_test.cpp.i
.PHONY : test/src/math/test/Matrix_test.cpp.i

test/src/math/test/Matrix_test.s: test/src/math/test/Matrix_test.cpp.s
.PHONY : test/src/math/test/Matrix_test.s

# target to generate assembly for a file
test/src/math/test/Matrix_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/math/test/Matrix_test.cpp.s
.PHONY : test/src/math/test/Matrix_test.cpp.s

test/src/mining/mining_pool_test.o: test/src/mining/mining_pool_test.c.o
.PHONY : test/src/mining/mining_pool_test.o

# target to build an object file
test/src/mining/mining_pool_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/mining/mining_pool_test.c.o
.PHONY : test/src/mining/mining_pool_test.c.o

test/src/mining/mining_pool_test.i: test/src/mining/mining_pool_test.c.i
.PHONY : test/src/mining/mining_pool_test.i

# target to preprocess a source file
test/src/mining/mining_pool_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/mining/mining_pool_test.c.i
.PHONY : test/src/mining/mining_pool_test.c.i

test/src/mining/mining_pool_test.s: test/src/mining/mining_pool_test.c.s
.PHONY : test/src/mining/mining_pool_test.s

# target to generate assembly for a file
test/src/mining/mining_pool_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/mining/mining_pool_test.c.s
.PHONY : test/src/mining/mining_pool_test.c.s

test/src/simple_profiling.o: test/src/simple_profiling.cpp.o
.PHONY : test/src/simple_profiling.o

# target to build an object file
test/src/simple_profiling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/simple_profiling.cpp.o
.PHONY : test/src/simple_profiling.cpp.o

test/src/simple_profiling.i: test/src/simple_profiling.cpp.i
.PHONY : test/src/simple_profiling.i

# target to preprocess a source file
test/src/simple_profiling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/simple_profiling.cpp.i
.PHONY : test/src/simple_profiling.cpp.i

test/src/simple_profiling.s: test/src/simple_profiling.cpp.s
.PHONY : test/src/simple_profiling.s

# target to generate assembly for a file
test/src/simple_profiling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/simple_profiling.cpp.s
.PHONY : test/src/simple_profiling.cpp.s

test/src/sorting/sorting_test.o: test/src/sorting/sorting_test.cpp.o
.PHONY : test/src/sorting/sorting_test.o

# target to build an object file
test/src/sorting/sorting_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/sorting/sorting_test.cpp.o
.PHONY : test/src/sorting/sorting_test.cpp.o

test/src/sorting/sorting_test.i: test/src/sorting/sorting_test.cpp.i
.PHONY : test/src/sorting/sorting_test.i

# target to preprocess a source file
test/src/sorting/sorting_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/sorting/sorting_test.cpp.i
.PHONY : test/src/sorting/sorting_test.cpp.i

test/src/sorting/sorting_test.s: test/src/sorting/sorting_test.cpp.s
.PHONY : test/src/sorting/sorting_test.s

# target to generate assembly for a file
test/src/sorting/sorting_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility_test.dir/build.make CMakeFiles/Utility_test.dir/test/src/sorting/sorting_test.cpp.s
.PHONY : test/src/sorting/sorting_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Utility"
	@echo "... Utility_test"
	@echo "... main/src/codec/hasher.o"
	@echo "... main/src/codec/hasher.i"
	@echo "... main/src/codec/hasher.s"
	@echo "... main/src/codec/json.o"
	@echo "... main/src/codec/json.i"
	@echo "... main/src/codec/json.s"
	@echo "... main/src/math/BigDecimal.o"
	@echo "... main/src/math/BigDecimal.i"
	@echo "... main/src/math/BigDecimal.s"
	@echo "... main/src/math/BigInteger.o"
	@echo "... main/src/math/BigInteger.i"
	@echo "... main/src/math/BigInteger.s"
	@echo "... main/src/math/ComplexNumber.o"
	@echo "... main/src/math/ComplexNumber.i"
	@echo "... main/src/math/ComplexNumber.s"
	@echo "... main/src/math/Matrix.o"
	@echo "... main/src/math/Matrix.i"
	@echo "... main/src/math/Matrix.s"
	@echo "... main/src/sorting/algorithm/bubble_sort.o"
	@echo "... main/src/sorting/algorithm/bubble_sort.i"
	@echo "... main/src/sorting/algorithm/bubble_sort.s"
	@echo "... main/src/sorting/algorithm/insertion_sort.o"
	@echo "... main/src/sorting/algorithm/insertion_sort.i"
	@echo "... main/src/sorting/algorithm/insertion_sort.s"
	@echo "... main/src/sorting/algorithm/merge_sort.o"
	@echo "... main/src/sorting/algorithm/merge_sort.i"
	@echo "... main/src/sorting/algorithm/merge_sort.s"
	@echo "... main/src/sorting/algorithm/selection_sort.o"
	@echo "... main/src/sorting/algorithm/selection_sort.i"
	@echo "... main/src/sorting/algorithm/selection_sort.s"
	@echo "... test/src/codec/codec_test.o"
	@echo "... test/src/codec/codec_test.i"
	@echo "... test/src/codec/codec_test.s"
	@echo "... test/src/codec/hasher_test.o"
	@echo "... test/src/codec/hasher_test.i"
	@echo "... test/src/codec/hasher_test.s"
	@echo "... test/src/main.o"
	@echo "... test/src/main.i"
	@echo "... test/src/main.s"
	@echo "... test/src/math/BigInteger_test.o"
	@echo "... test/src/math/BigInteger_test.i"
	@echo "... test/src/math/BigInteger_test.s"
	@echo "... test/src/math/ComplexNumber_test.o"
	@echo "... test/src/math/ComplexNumber_test.i"
	@echo "... test/src/math/ComplexNumber_test.s"
	@echo "... test/src/math/math_test.o"
	@echo "... test/src/math/math_test.i"
	@echo "... test/src/math/math_test.s"
	@echo "... test/src/math/test/Matrix_test.o"
	@echo "... test/src/math/test/Matrix_test.i"
	@echo "... test/src/math/test/Matrix_test.s"
	@echo "... test/src/mining/mining_pool_test.o"
	@echo "... test/src/mining/mining_pool_test.i"
	@echo "... test/src/mining/mining_pool_test.s"
	@echo "... test/src/simple_profiling.o"
	@echo "... test/src/simple_profiling.i"
	@echo "... test/src/simple_profiling.s"
	@echo "... test/src/sorting/sorting_test.o"
	@echo "... test/src/sorting/sorting_test.i"
	@echo "... test/src/sorting/sorting_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

