name: AUTO

on:
  push:
    paths:
      - 'profiling_util/**'
      - 'math_util/**'
      - 'codec_util/**'

permissions:
  actions: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Filter Formating Files
        uses: dorny/paths-filter@v3.0.1
        id: files
        with:
          list-files: shell
          filters: |
            profiling_util:
              - 'profiling_util/**'
            math_util:
              - 'math_util/**'
            codec_util:
              - 'codec_util/**'
            src:
              - added|modified: '**/*.cpp'
              - added|modified: '**/*.hpp'

      - name: Formating and Save changes File
        if: steps.files.outputs.src == 'true'
        run: |
          sudo apt-get install -y clang-format
          echo ${{ steps.files.outputs.src_files }} | xargs -n 1 clang-format -i
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          git commit -m "changes of formating"
          git push

      - name: Run Test For profiling_util
        if: steps.files.outputs.profiling_util == 'true'
        run: gradle :profiling_util:test

      - name: Run Test For math_util
        if: steps.files.outputs.math_util == 'true'
        run: gradle :math_util:test

      - name: Run Test For codec_util
        if: steps.files.outputs.codec_util == 'true'
        run: gradle :codec_util:test

