name: AUTO

on:
  push:
    paths:
      - '.github/workflows/auto.yml'
      - 'main/**'
      - 'test/**'

jobs:
  formating-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build and Run Test
        run: make Test

