name: AUTO

on:
  push:
    paths:
      - '.github/workflows/auto.yml'
      - 'profiling_util/**'
      - 'math_util/**'
      - 'codec_util/**'

permissions:
  actions: write
  contents: write

jobs:
  test-profiling:
    outputs:
      math: ${{ steps.files.outputs.math_util }}
      codec: ${{ steps.files.outputs.codec_util }}
      hash: ${{ steps.files.outputs.hash_util }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Filtering
        uses: dorny/paths-filter@v3.0.1
        id: files
        with:
          list-files: shell
          filters: |
            profiling_util:
              - 'profiling_util/**'
            math_util:
              - 'math_util/**'
            codec_util:
              - 'codec_util/**'
            src:
              - added|modified: '**/*.cpp'
              - added|modified: '**/*.hpp'
              - added|modified: '**/*.c'
              - added|modified: '**/*.h'

      - name: Formating Src File
        if: steps.files.outputs.src == 'true'
        run: |
          sudo apt-get install -y clang-format
          echo ${{ steps.files.outputs.src_files }} | xargs -n 1 clang-format -i

      - name: Push Change
        continue-on-error: true
        run: |
          git add .
          if (git commit -m "Reformatting Code Sources"); then
            git config --global user.email "ikomangwidiadaariasa12@gmail.com"
            git config --global user.name "AriasaProp"
            git push
          fi

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

      - name: Run Test
        run: |
          build/math_util/math_test math_util
          build/codec_util/codec_test codec_util/data
          
