name: AUTO

on:
  push:
    paths:
      - '.github/workflows/auto.yml'
      - 'profiling_util/**'
      - 'math_util/**'
      - 'codec_util/**'

permissions:
  actions: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Filter Formating Files
        uses: dorny/paths-filter@v3.0.1
        id: files
        with:
          list-files: shell
          filters: |
            profiling_util:
              - 'profiling_util/**'
            math_util:
              - 'math_util/**'
            codec_util:
              - 'codec_util/**'
            src:
              - added|modified: '**/*.cpp'
              - added|modified: '**/*.hpp'

      - uses: gradle/actions/setup-gradle@v3
      
      - name: Formating Src File
        if: steps.files.outputs.src == 'true'
        continue-on-error: true
        run: |
          sudo apt-get install -y clang-format
          echo ${{ steps.files.outputs.src_files }} | xargs -n 1 clang-format -i
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          git commit -m "changes of formating"
          git push

      - name: Setup Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Tests
        run: |
          if [ "${{ steps.files.outputs.profiling_util }}" == "true" ]; then
            gradle :profiling_util:test
          fi
          if [ "${{ steps.files.outputs.math_util }}" == "true" ]; then
            gradle :math_util:test
          fi
          if [ "${{ steps.files.outputs.codec_util }}" == "true" ]; then
            gradle :codec_util:test
          fi


