name: AUTO

on: [push]

permissions:
  actions: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run Test
        run: gradle test

      - name: Filter Formating Files
        uses: dorny/paths-filter@v3.0.1
        id: files
        with:
          list-files: shell
          filters: |
            src:
              - added|modified: '**/*.cpp'
              - added|modified: '**/*.hpp'

      - name: Formating and Save changes File
        run: |
          echo ${{ steps.files.outputs.src_files }}
          sudo apt-get install -y clang-format
          find . -iname "*.cpp" -o -iname "*.hpp" | xargs -n 1 clang-format -i
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          git commit -m "changes of formating"
          git push

