name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'main/**'
      - 'test/**'
      - 'benchmark/**'
      - 'run/**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-11-arm, windows-2025, ubuntu-slim, ubuntu-26.04, ubuntu-26.04-arm]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest
      - run: gcc run/nob.c -o run/nob -I./run
      - run: run/nob test
      - run: run/nob benchmark 

